### ISSUE TITLE
Home Buttons styling inconsistent between devices

### ISSUE THREAD

**Issue by zach-daniels** [sometimeapp/SomeTimeApp#40]
[https://i.imgur.com/rJK5Woy.jpg](url)

**Comment by MrSamsa42** [comment]
I'm pretty sure this is working -- i tested it on the iPhone 5s and my Pixel 2XL, and both render the button text the same way.  
See here for more info and alternatives: https://stackoverflow.com/questions/33628677/react-native-responsive-font-size
